"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-14 03:51:25.702424

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_entries",
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("query_normalized", sa.Text(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("query_hash"),
    )
    with op.batch_alter_table("cache_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cache_entries_last_used_at"), ["last_used_at"], unique=False
        )

    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name_pt", sa.String(length=128), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("monthly_credits", sa.Integer(), nullable=False),
        sa.Column("price_brl_cents", sa.Integer(), nullable=False),
        sa.Column("validity_days", sa.Integer(), nullable=False),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doi", sa.String(length=256), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("authors_json", sa.JSON(), nullable=True),
        sa.Column("journal", sa.String(length=512), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("pdf_url", sa.Text(), nullable=True),
        sa.Column("oa_status", sa.String(length=32), nullable=True),
        sa.Column("citations", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_articles_category_id"), ["category_id"], unique=False)
        batch_op.create_index("ix_articles_category_year", ["category_id", "year"], unique=False)
        batch_op.create_index(batch_op.f("ix_articles_doi"), ["doi"], unique=True)
        batch_op.create_index(batch_op.f("ix_articles_year"), ["year"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("current_plan_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_last_seen"), ["last_seen"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_telegram_id"), ["telegram_id"], unique=True)

    op.create_table(
        "credit_balances",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("monthly_quota_used", sa.Integer(), nullable=False),
        sa.Column("quota_resets_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("amount_brl_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_payment_ref", sa.String(length=128), nullable=True),
        sa.Column("provider_event_id", sa.String(length=128), nullable=True),
        sa.Column("pix_qr_code", sa.Text(), nullable=True),
        sa.Column("checkout_url", sa.Text(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_event_id"),
        sa.UniqueConstraint("provider_payment_ref"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index("ix_payments_event_id", ["provider_event_id"], unique=False)
        batch_op.create_index("ix_payments_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "search_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("query_raw", sa.Text(), nullable=False),
        sa.Column("query_normalized", sa.Text(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("articles_returned", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("search_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_search_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_search_logs_query_normalized"), ["query_normalized"], unique=False
        )
        batch_op.create_index(
            "ix_search_logs_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_search_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("current_period_end", sa.DateTime(), nullable=False),
        sa.Column("cancel_at", sa.DateTime(), nullable=True),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_subscription_ref", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index("ix_subscriptions_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "credit_transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("search_log_id", sa.Integer(), nullable=True),
        sa.Column("payment_id", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["search_log_id"],
            ["search_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("credit_transactions", schema=None) as batch_op:
        batch_op.create_index("ix_credit_transactions_expires", ["expires_at"], unique=False)
        batch_op.create_index(
            "ix_credit_transactions_user_created", ["user_id", "created_at"], unique=False
        )

    op.create_table(
        "search_articles",
        sa.Column("search_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["search_logs.id"],
        ),
        sa.PrimaryKeyConstraint("search_id", "article_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_articles")
    with op.batch_alter_table("credit_transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_credit_transactions_user_created")
        batch_op.drop_index("ix_credit_transactions_expires")

    op.drop_table("credit_transactions")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index("ix_subscriptions_user_status")

    op.drop_table("subscriptions")
    with op.batch_alter_table("search_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_logs_user_id"))
        batch_op.drop_index("ix_search_logs_user_created")
        batch_op.drop_index(batch_op.f("ix_search_logs_query_normalized"))
        batch_op.drop_index(batch_op.f("ix_search_logs_created_at"))

    op.drop_table("search_logs")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index("ix_payments_user_status")
        batch_op.drop_index("ix_payments_event_id")

    op.drop_table("payments")
    op.drop_table("credit_balances")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_telegram_id"))
        batch_op.drop_index(batch_op.f("ix_users_last_seen"))

    op.drop_table("users")
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_articles_year"))
        batch_op.drop_index(batch_op.f("ix_articles_doi"))
        batch_op.drop_index("ix_articles_category_year")
        batch_op.drop_index(batch_op.f("ix_articles_category_id"))

    op.drop_table("articles")
    op.drop_table("plans")
    op.drop_table("categories")
    with op.batch_alter_table("cache_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cache_entries_last_used_at"))

    op.drop_table("cache_entries")
    # ### end Alembic commands ###
